vk-to-kafka-service:
  vk-programming-keywords:
    - java
    - python
    - программирование
    - прикол
    - кот
    - хобби
    - чтение
    - читаю
    - читайтекниги
    - читаемвместе
    - литература
    - танцы
    - танец
    - танцуем
    - танцульки
    - танцули
    - танцуй
    - танцор
    - танцоры
    - танцуютвсе
    - танцыдоутра
    - танцытанцы
    - танцуйпокамолодой
    - танцпол
    - фото
    - фотосессия
    - фотограф
    - фотография
    - фотосет
    - фотодня
    - фотостудия
    - фотодляроссии
    - фотосъемка
    - фотопроект
    - фотографии
    - фотоотчет
    - фотомодель
    - фотоаппарат
    - фотографирую
    - фотозона
    - фотофан
    - фотографы
    - фотоархив
    - фотокарточка
    - фотка
    - фотки
    - искусство
    - искусство
    - творчество
    - декор
    - творю
    - творение
    - творческийпроцесс
    - творим
    - творческаямастерская
    - краскижизни
    - картина
    - картины
    - слушаюмузыку
    - музыка
    - музыканты
    - музыкант
    - музыкальный
    - музыканассвязала
    - музыкадлядуши
    - музыкантынасвадьбу
    - мелодиядуши
    - группа
    - исполнение
    - исполнитель
    - книга
    - книги
    - книголюб
    - книгоман
    - книжныйчервь
    - книжка
    - книжнаяполка
    - книжки
    - книжныйманьяк
    - книгалучшийподарок
    - книгиэтосчастье
    - книгинашевсе
    - illustrations
    - picture
    - pictureoftheday
    - artpop
    - artstagram
    - artlife
    - art
    - illustration
    - pictures
    - drawing
    - artwork
    - artsy
    - sketch
    - artoftheday
    - photo
    - photooftheday
    - photogrid
    - photoshoot
    - photographer
    - photos
    - music
    - musica

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  max-attempts: 3
  sleep-time-ms: 2000

kafka-config:
  bootstrap-servers: localhost:9092, localhost:19092, localhost:29092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topic-name: vk_stream
  topic-name-to-create:
    - vk_stream
  num-of-partitions: 3
  replication-factor: 3